#!/bin/ksh

INTERVAL=${1:-10}
HOSTNAME="${COLLECTD_HOSTNAME:-$(/bin/hostname)}"
SUDO=sudo
SYSLOG_NG_CTL="syslog-ng-ctl"
AWK="awk"
PLUGIN="syslog_ng"

while :; do
	$SUDO $SYSLOG_NG_CTL stats | $AWK -vinterval=$INTERVAL -vhost=$HOSTNAME -vplugin=$PLUGIN -F\; 'NR!=1 && $1 != "src.none" {if ($2 == "") { t=$3 } else {t=$2} printf "PUTVAL %s/%s-%s/derive-%s %s:%s interval=%s\n",host,plugin,t,$5,systime(),$6,interval}'
	sleep $INTERVAL
done

